//Constants that the reducer uses for switch cases

export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS",
GET_GROUP_FAIL = "GET_GROUP_FAIL",
DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS",
DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL",
CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS",
CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL",
UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS",
UPDATE_GROUP_FAIL = "UPDATE_GROUP_FAIL"


