//Constants that the reducer uses for switch cases

export const LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  AUTHENTICATED = "AUTHENTICATED",
  CHECK_TOKEN = "CHECK_TOKEN",
  LOGOUT = "LOGOUT",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
