//Constants that the reducer uses for switch cases

export const LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  AUTHENTICATED = "AUTHENTICATED",
  CHECK_TOKEN = "CHECK_TOKEN",
  LOGOUT = "LOGOUT",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  GET_USER_SUCCESS = "GETUSER_SUCCESS",
  GET_USER_FAIL = "GET_USER_FAIL",
  USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS",
  USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
